kotlin.code.style=official
kotlin.js.compiler=ir
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.enableJetifier=true
android.compileSdk=34
android.targetSdk=34
android.minSdk=26

# Versions
kotlin.version=1.9.22
agp.version=8.2.0
compose.version=1.5.12
