kotlin.code.style=official
org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=false
android.useAndroidX=true
android.enableJetifier=true
android.compileSdk=35
android.targetSdk=35
android.minSdk=26

# Versions
kotlin.version=1.9.25
agp.version=8.7.2
compose.version=1.5.15
